---
name: golangci-lint
'on':
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.17
      - uses: actions/checkout@v3.1.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          # Required: the version of golangci-lint is required and must be
          # specified without patch version: we always use the latest patch
          version: v1.44
