---
name: MegaLinter
"on": [push]

# checkov complains about the default, we don't need more for now, but if we ever want megalinter
# to fix things for us, we'll have to revisit
permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: read

jobs:
  mega-lint:
    name: Mega Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go build ./...
      - name: Mega Linter
        uses: megalinter/megalinter/flavors/go@v8.8.0
        env:
          # VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          # Validates all source when push on main, else just the git diff with main.
          # Override with true if you always want to lint all sources
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_LINTERS: SPELL_CSPELL
          DISABLE_ERRORS_LINTERS: COPYPASTE_JSCPD,REPOSITORY_TRIVY,
          # GO_GOLANGCI_LINT_CLI_LINT_MODE: project
          GO_REVIVE_CLI_LINT_MODE: project
          # yes, I did put a fake slack token in my code... get over it
          REPOSITORY_SECRETLINT_DISABLE_ERRORS: true
